<?php
include "../includes/header.php";
require_once __DIR__ . "/../includes/db.php";

$blockedDates = [];
$bookedSlots = [];

try {
    $stmt = $pdo->query('SELECT blocked_date FROM blocked_dates');
    $blockedDates = $stmt->fetchAll(PDO::FETCH_COLUMN);

    $stmt2 = $pdo->query('SELECT date, time FROM bookings WHERE status <> "cancelled"');
    $bookedSlots = $stmt2->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    // fallback if DB unavailable
    $blockedDates = [];
    $bookedSlots = [];
}
?>
<!DOCTYPE html>
<html lang="nl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Boek een sessie - Mark Cox Training</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../css/styles.css">
  <link rel="stylesheet" href="../css/booking.css">
  <style>
    .page-hero {
      padding: 8rem 0 4rem;
      background-color: #111111;
      position: relative;
      overflow: hidden;
    }
    
    .booking-container {
      max-width: 1280px;
      margin: 0 auto;
      padding: 3rem 1.5rem;
      min-height: 60vh;
    }
    
    .time-slots {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 0.5rem;
      margin-top: 1rem;
    }
    
    .time-slot {
      padding: 0.75rem;
      border: 1px solid rgba(255, 255, 255, 0.15);
      border-radius: 0.75rem;
      background: none;
      color: rgba(255, 255, 255, 0.6);
      font-size: 0.85rem;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.15s;
    }
    
    .time-slot:hover {
      border-color: rgba(232, 88, 10, 0.5);
      color: white;
    }
    
    .time-slot.selected {
      background-color: #e8580a;
      border-color: #e8580a;
      color: white;
    }
    
    .booking-grid {
      display: grid;
      grid-template-columns: 2fr 1fr;
      gap: 2rem;
    }
    
    .success-message {
      text-align: center;
      padding: 4rem 2rem;
    }
    
    .success-icon {
      width: 80px;
      height: 80px;
      background-color: rgba(232, 88, 10, 0.2);
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto 2rem;
      font-size: 2.5rem;
    }

    .calendar-day.partially-booked {
      background: rgba(232, 88, 10, 0.12);
      border-color: rgba(232, 88, 10, 0.5);
      color: #fff;
    }
    
    @media (max-width: 1023px) {
      .booking-grid {
        grid-template-columns: 1fr;
      }
    }
  </style>
</head>
<body>
 
  <div class="page-hero">
    <div class="container">
      <div class="hero-label">
        <span>Boeking</span>
      </div>
      <h1 style="font-size: clamp(2.2rem, 5vw, 3.8rem); font-weight: 800; margin-bottom: 1rem;">
        BOEK JE SESSIE<br>
        
      </h1>
      <p style="color: rgba(255, 255, 255, 0.5); max-width: 600px;">
        Kies een datum en tijd en vul je gegevens in. Mark bevestigt binnen 24 uur.
      </p>
    </div>
  </div>

  <!-- Booking Content -->
  <div class="booking-container" id="bookingContent">
    <div class="booking-grid">
      <!-- Calendar -->
      <div class="calendar" id="calendarContainer">
        <div class="calendar-header">
          <button class="calendar-nav-btn" onclick="previousMonth()">‹</button>
          <div class="calendar-title" id="monthTitle">januari 2026</div>
          <button class="calendar-nav-btn" onclick="nextMonth()">›</button>
        </div>
        
        <div class="calendar-weekdays">
          <div class="calendar-weekday">Ma</div>
          <div class="calendar-weekday">Di</div>
          <div class="calendar-weekday">Wo</div>
          <div class="calendar-weekday">Do</div>
          <div class="calendar-weekday">Vr</div>
          <div class="calendar-weekday">Za</div>
          <div class="calendar-weekday">Zo</div>
        </div>
        
        <div class="calendar-days" id="calendarDays">
          <!-- Days will be generated by JavaScript -->
        </div>
        
        <div style="display: flex; gap: 1.5rem; margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid rgba(255, 255, 255, 0.1);">
          <div style="display: flex; align-items: center; gap: 0.5rem;">
            <div style="width: 12px; height: 12px; background-color: #e8580a; border-radius: 4px;"></div>
            <span style="color: rgba(255, 255, 255, 0.5); font-size: 0.72rem;">Geselecteerd</span>
          </div>
          <div style="display: flex; align-items: center; gap: 0.5rem;">
            <div style="width: 12px; height: 12px; background-color: rgba(232, 88, 10, 0.25); border-radius: 4px;"></div>
            <span style="color: rgba(255, 255, 255, 0.5); font-size: 0.72rem;">Gedeeltelijk geboekt</span>
          </div>
          <div style="display: flex; align-items: center; gap: 0.5rem;">
            <div style="width: 12px; height: 12px; background-color: rgba(139, 0, 0, 0.5); border-radius: 4px;"></div>
            <span style="color: rgba(255, 255, 255, 0.5); font-size: 0.72rem;">Niet beschikbaar</span>
          </div>
        </div>
      </div>
      
      <!-- Time Selection -->
      <div class="card" style="height: fit-content; position: sticky; top: 90px;">
        <h3 style="font-weight: 700; margin-bottom: 1rem;" id="dateTitle">Kies eerst een datum</h3>
        <div id="timeSlotContainer">
          <div style="text-align: center; padding: 3rem 1rem;">
            <div style="font-size: 3rem; opacity: 0.2; margin-bottom: 1rem;">📅</div>
            <p style="color: rgba(255, 255, 255, 0.3); font-size: 0.85rem;">
              Kies een dag in de kalender om beschikbare tijden te zien
            </p>
          </div>
        </div>
        
        <button id="continueBtn" class="btn btn-primary" style="width: 100%; margin-top: 1.5rem; display: none;" onclick="showBookingForm()">
          DOORGAAN →
        </button>
      </div>
    </div>
    
    <!-- Booking Form (Hidden Initially) -->
    <div id="bookingForm" class="hidden">
      <div style="max-width: 700px; margin: 0 auto;">
        <div class="card">
          <div style="background-color: rgba(232, 88, 10, 0.1); border: 1px solid rgba(232, 88, 10, 0.2); border-radius: 0.75rem; padding: 1rem; margin-bottom: 2rem; display: flex; align-items: center; gap: 0.75rem;">
            <div style="font-size: 1.25rem;">📅</div>
            <div>
              <p style="font-weight: 600; font-size: 0.9rem;" id="formDateDisplay"></p>
              <p style="color: #e8580a; font-size: 0.8rem;" id="formTimeDisplay"></p>
            </div>
          </div>
          
          <h3 style="font-size: 1.3rem; font-weight: 700; margin-bottom: 1.5rem;">Je gegevens</h3>
          
          <form onsubmit="submitBooking(event)">
            <div class="form-group">
              <label class="form-label">Volledige naam *</label>
              <input type="text" class="form-input" id="nameInput" required placeholder="Je volledige naam">
            </div>
            
            <div class="form-group">
              <label class="form-label">E-mailadres *</label>
              <input type="email" class="form-input" id="emailInput" required placeholder="jij@email.com">
            </div>
            
            <div class="form-group">
              <label class="form-label">Telefoonnummer</label>
              <input type="tel" class="form-input" id="phoneInput" placeholder="+31 6 ...">
            </div>
            
            <div class="form-group">
              <label class="form-label">Programma *</label>
              <select class="form-select" id="programInput" required>
                <option value="" disabled selected>Kies een programma</option>
                <option value="1-op-1 Personal Training">1-op-1 Personal Training</option>
                <option value="Outdoor Bootcamp">Outdoor Bootcamp</option>
                <option value="Kracht & Prestaties">Kracht & Prestaties</option>
                <option value="Voedingscoaching">Voedingscoaching</option>
                <option value="Gratis consult">Gratis consult</option>
              </select>
            </div>
            
            <div class="form-group">
              <label class="form-label">Extra opmerkingen</label>
              <textarea class="form-textarea" id="notesInput" placeholder="Blessures, doelen of vragen?"></textarea>
            </div>
            
            <div style="display: flex; gap: 1rem; margin-top: 2rem;">
              <button type="button" class="btn btn-secondary" style="flex: 1;" onclick="backToCalendar()">
                ← TERUG
              </button>
              <button type="submit" class="btn btn-primary" style="flex: 2;">
                BEVESTIG BOEKING ✓
              </button>
              <a href="/pages/admin-calendar.php">hiiiii</a>

            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    // Pass PHP data to JavaScript
    window.DB_BLOCKED_DATES = new Set(<?= json_encode($blockedDates) ?>);
    window.DB_BOOKED_SLOTS = <?= json_encode($bookedSlots) ?>;
  </script>
  <script src="../js/main.js"></script>
  <script src="../js/booking.js"></script>
</body>
</html>
<?php
include '../includes/footer.php';
?>
